# Generated by Django 3.1.6 on 2021-02-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fristname',
            new_name='frist_name',
        ),
    ]
