# Generated by Django 3.1.6 on 2021-02-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210204_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
